PRODUCTS = [
    ("biodiesel", "Biodiesel"),
    ("bioetanol", "Bioetanol"),
    ("gas-natural-comprimido", "Gas Natural Comprimido"),
    ("gas-natural-licuado", "Gas Natural Licuado"),
    ("gases-licuados-del-petroleo", "Gases licuados del petróleo"),
    ("gasoleo-a", "Gasoleo A"),
    ("gasoleo-b", "Gasoleo B"),
    ("gasoleo-premium", "Gasoleo Premium"),
    ("gasolina-95-e10", "Gasolina 95 E10"),
    ("gasolina-95-e5", "Gasolina 95 E5"),
    ("gasolina-95-e5-premium", "Gasolina 95 E5 Premium"),
    ("gasolina-98-e10", "Gasolina 98 E10"),
    ("gasolina-98-e5", "Gasolina 98 E5"),
    ("hidrogeno", "Hidrogeno"),
]
